const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='mls-v3';
const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const AR_DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const PRAYERS=['Fajr','Dhuhr','Asr','Maghrib','Isha'];
const BODY=['Head','Eyes','Ears','Nose','Mouth/Teeth','Neck','Shoulders','Upper Back','Lower Back','Chest','Abdomen','Elbows','Wrists','Hands','Hips','Thighs','Knees','Calves','Ankles','Feet'];
const defaultState={lang:'en',theme:'aurora',background:'aurora',city:'Cairo',country:'Egypt',date:null,prayer:{},sleep:{hours:8,quality:3,bed:'',wake:''},water:0,waterGoal:8,walk:0,walkGoal:30,studyMinutes:0,screen:0,mood:3,energy:3,habits:[{id:1,name:'Wake up on time',done:false},{id:2,name:'Read',done:false},{id:3,name:'Walk',done:false}],hygiene:[],tasks:[],events:[],subjects:[],assignments:[],exams:[],grades:[],body:{},journal:'',wins:'',gratitude:'',income:0,expenses:[],savingsTarget:0,savingsSaved:0,phoneTarget:'New phone',priorities:[],focus:{sessions:0,minutes:0},history:{},settings:{sound:true,notifications:false},lastPrayer:null,smart:{auto:false,energy:'medium'},lifeMap:{},reminders:[]};
let state=load(); let view='home'; let timer={sec:25*60,running:false,id:null,mode:'focus'};
function load(){let s={...defaultState};try{s={...s,...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{};normalize(s);ensureDay(s);return s}
function normalize(s){['habits','hygiene','tasks','events','subjects','assignments','exams','grades','priorities'].forEach(k=>s[k]=Array.isArray(s[k])?s[k]:[]);s.history=s.history||{};s.prayer=s.prayer||{};s.body=s.body||{};s.expenses=s.expenses||[];s.settings={...defaultState.settings,...(s.settings||{})};s.music={youtube:'',audioUrl:'',title:'',...(s.music||{})}}
function todayKey(d=new Date()){return d.toISOString().slice(0,10)}
function ensureDay(s){const k=todayKey();if(s.date!==k){if(s.date){s.history[s.date]=snapshot(s)}s.date=k;s.water=0;s.walk=0;s.studyMinutes=0;s.screen=0;s.mood=3;s.energy=3;s.prayer={};s.hygiene=[];s.body={};s.journal='';s.wins='';s.gratitude='';s.focus={sessions:0,minutes:0};s.habits=s.habits.map((h,i)=>({...h,done:false,id:h.id||Date.now()+i}));s.priorities=s.priorities.map(p=>({...p,done:false}));save()}}
function snapshot(s){return {water:s.water,walk:s.walk,study:s.studyMinutes,sleep:s.sleep.hours,mood:s.mood,energy:s.energy,focus:s.focus.sessions,habits:s.habits.filter(x=>x.done).length,tasks:s.tasks.filter(x=>x.done).length,prayers:Object.values(s.prayer).filter(Boolean).length}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function t(key){const ar={
'nav.home':'الرئيسية','nav.planner':'المخطط','nav.university':'الجامعة','nav.health':'الصحة','nav.habits':'العادات','nav.hygiene':'النظافة','nav.finance':'المال','nav.focus':'التركيز','nav.journal':'اليوميات','nav.analytics':'التحليلات','nav.music':'الموسيقى والقرآن','nav.settings':'الإعدادات'};const en={'nav.home':'Home','nav.planner':'Planner','nav.university':'University','nav.health':'Health','nav.habits':'Habits','nav.hygiene':'Hygiene','nav.finance':'Finance','nav.focus':'Focus','nav.journal':'Journal','nav.analytics':'Analytics','nav.music':'Music & Quran','nav.settings':'Settings'};return state.lang==='ar'?(ar[key]||key):(en[key]||key)}
function fmtDate(){const d=new Date();return state.lang==='ar'?d.toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long'}):d.toLocaleDateString('en',{weekday:'long',day:'numeric',month:'long'})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function sound(){if(!state.settings.sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=660;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.08)}catch{}}
function score(){const p=Object.values(state.prayer).filter(Boolean).length/5;const sleep=Math.max(0,1-Math.abs(state.sleep.hours-8)/5);const water=Math.min(1,state.water/state.waterGoal);const walk=Math.min(1,state.walk/state.walkGoal);const study=Math.min(1,state.studyMinutes/120);const habits=state.habits.length?state.habits.filter(h=>h.done).length/state.habits.length:0;const hygiene=state.hygiene.length?state.hygiene.filter(Boolean).length/8:0;const tasks=state.tasks.filter(x=>x.done).length/(Math.max(1,state.tasks.length));return Math.round((p*.14+sleep*.15+water*.1+walk*.12+study*.15+habits*.12+hygiene*.08+tasks*.14)*100)}
function lifeMap(){
 const d=new Date(), y=d.getFullYear(), m=d.getMonth(), days=new Date(y,m+1,0).getDate();
 const cells=[]; for(let i=1;i<=days;i++){const k=todayKey(new Date(y,m,i));const h=state.history[k];const active=k===todayKey();const sc=active?score():h?Math.round(((h.prayers/5)*20+(Math.min(1,h.sleep/8))*20+(Math.min(1,h.water/8))*15+(Math.min(1,h.walk/30))*15+(Math.min(1,h.study/120))*15+(Math.min(1,h.habits/Math.max(1,state.habits.length)))*15)):0;cells.push(`<div class="life-day ${active?'today':''}" title="${k}"><b>${i}</b><span style="--p:${sc}%"></span><small>${sc}</small></div>`)}
 const savePct=state.savingsTarget?Math.min(100,Math.round(state.savingsSaved/state.savingsTarget*100)):0;
 return `${head('LIFE MAP','Life Map','A single visual map of your month — sleep, movement, study, prayer, habits and money.')}
 <div class="grid grid-3"><div class="card hero"><div><div class="eyebrow">PHONE GOAL</div><h2>${savePct}%</h2><p>${esc(state.phoneTarget||'New phone')} · ${n(state.savingsSaved).toLocaleString()} / ${n(state.savingsTarget).toLocaleString()}</p></div></div>${metric('🎓',state.subjects.length,'Subjects')}${metric('🔥',state.habits.filter(x=>x.done).length,'Habits today')}</div>
 ${sectionBox('🗺️ Monthly rhythm',`<div class="life-grid">${cells.join('')}</div>`)}
 <div class="grid grid-2" style="margin-top:16px">${sectionBox('🎯 Life domains',domainBars())}${sectionBox('💡 This month',monthlyInsights())}</div>`}
function sectionBox(title,body){return `<section class="card"><div class="card-head"><h3>${title}</h3></div>${body}</section>`}
function domainBars(){const vals=[['😴 Sleep',Math.min(100,state.sleep.hours/8*100)],['📚 Study',Math.min(100,state.studyMinutes/120*100)],['🚶 Walk',Math.min(100,state.walk/30*100)],['💧 Water',Math.min(100,state.water/state.waterGoal*100)],['🕌 Prayer',Object.values(state.prayer).filter(Boolean).length/5*100],['🔥 Habits',state.habits.length?state.habits.filter(x=>x.done).length/state.habits.length*100:0]];return vals.map(x=>`<div class="domain"><div><span>${x[0]}</span><b>${Math.round(x[1])}%</b></div><div class="progress"><span style="width:${x[1]}%"></span></div></div>`).join('')}
function monthlyInsights(){const a=[];if(state.sleep.hours<7)a.push('Your default sleep target is below 7h — protect your bedtime first.');if(state.studyMinutes>=120)a.push('You already have a strong study block today.');if(state.walk>=30)a.push('Movement target reached — keep it easy and consistent.');if(state.savingsTarget&&state.savingsSaved/state.savingsTarget<.25)a.push('Your phone goal is still early; define a weekly saving amount.');return a.length?a.map(x=>`<p class="insight">✨ ${x}</p>`).join(''):'<p class="insight">✨ Keep logging for a few days so the system can find patterns that are actually yours.</p>'}
function smartday(){
 const tasks=state.tasks.filter(x=>!x.done).sort((a,b)=>(Number(a.priority||3)-Number(b.priority||3)) || String(a.date).localeCompare(String(b.date)));const blocks=tasks.slice(0,6);const energy=state.energy>=4?'high':state.energy<=2?'low':'medium';const suggestion=energy==='high'?'Put the hardest university task in your next 60–90 minute block.':energy==='low'?'Keep the next block light: review, organize, walk or recover.':'Use one focused study block, then a short movement break.';
 return `${head('ADAPTIVE PLANNER','Smart Day','The system turns your real data into a practical plan — without pretending to know you better than you do.')}
 <div class="card hero"><div><div class="eyebrow">ENERGY MODE · ${energy.toUpperCase()}</div><h2>${suggestion}</h2><p>Current Life Pulse: ${score()}/100</p></div></div>
 <div class="grid grid-2" style="margin-top:16px">${sectionBox('🧠 Recommended order',blocks.length?`<div class="timeline">${blocks.map((x,i)=>`<div class="timeline-item"><div class="time">${i+1}</div><div class="time-card"><b>${esc(x.title)}</b><small>${x.date||todayKey()} ${x.time||''} · Priority ${x.priority||3}</small></div></div>`).join('')}</div>`:'<div class="empty">No unfinished tasks. Add a few outcomes first.</div>')}${sectionBox('🧩 Planning rules',`<div class="list"><div class="row"><span>🎯</span><div class="row-main"><b>One important outcome</b><small>Do not overload the day.</small></div></div><div class="row"><span>⏱️</span><div class="row-main"><b>Focus in blocks</b><small>Use Pomodoro when the task feels heavy.</small></div></div><div class="row"><span>🚶</span><div class="row-main"><b>Movement break</b><small>Use a short walk between demanding blocks.</small></div></div><div class="row"><span>🌙</span><div class="row-main"><b>Protect sleep</b><small>Do not trade tomorrow's energy for low-value work.</small></div></div></div>`)}</div>`}
function insights(){const tips=[];if(state.sleep.hours<7)tips.push('Sleep is your first lever: aim for a consistent bedtime rather than chasing one perfect night.');if(state.screen>6)tips.push('Screen time is high today. Try a phone-free focus block.');if(state.studyMinutes>0&&state.studyMinutes<60)tips.push('A small study block is already a win — add 25 focused minutes rather than waiting for a perfect session.');if(state.water<state.waterGoal/2)tips.push('Hydration is behind your goal; spread water across the remaining hours instead of catching up at once.');if(state.walk<15)tips.push('A short walk can be the lowest-friction movement option on a busy day.');if(!tips.length)tips.push('Your current signals are balanced. Keep the routine stable and collect more days before changing it.');return `${head('PERSONAL INTELLIGENCE','Insights','Suggestions are generated from your own logs and stay on your device.')}
 <div class="grid grid-2">${tips.map((x,i)=>`<div class="card insight-card"><span>${['💡','🧠','⚡','🌱'][i%4]}</span><h3>${['Sleep','Focus','Health','Consistency'][i%4]}</h3><p>${x}</p></div>`).join('')}</div>
 ${sectionBox('🔔 Reminders',`<div class="form-grid"><div class="field"><label>Reminder title</label><input class="input" id="remTitle"></div><div class="field"><label>Date & time</label><input class="input" id="remAt" type="datetime-local"></div><button class="btn primary" id="addRem">Add reminder</button><button class="btn" id="notifyBtn">Enable notifications</button></div><div class="list" style="margin-top:12px">${(state.reminders||[]).map(r=>`<div class="row"><div class="row-main"><b>${esc(r.title)}</b><small>${r.at}</small></div></div>`).join('')||'<div class="empty">No reminders yet.</div>'}</div>`)}`}
function render(){document.documentElement.lang=state.lang;document.body.classList.toggle('rtl',state.lang==='ar');document.body.classList.toggle('ltr',state.lang==='en');$('#sideDate').textContent=fmtDate();$('#langBtn').textContent=state.lang==='en'?'العربية':'English';$('#themeBtn').textContent=state.theme==='night'?'🌙':'☀️';$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const fn={home:home,lifemap:lifeMap,smartday:smartday,insights:insights,planner:planner,university:university,health:health,habits:habits,hygiene:hygiene,finance:finance,focus:focus,journal:journal,analytics:analytics,music:music,settings:settings}[view]||home;$('#app').innerHTML=fn();bind();}
function head(ey,title,sub=''){return `<div class="view-head"><div><div class="eyebrow">${ey}</div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="btn-row"><button class="btn soft" data-action="quick">＋ Quick Add</button></div></div>`}
function home(){const sc=score();const todayTasks=state.tasks.filter(x=>!x.done).slice(0,5);const upcoming=[...state.events,...state.exams.map(x=>({...x,type:'exam'})),...state.assignments.map(x=>({...x,type:'assignment'}))].filter(x=>x.date>=todayKey()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);return `${head('DAILY COMPASS',state.lang==='ar'?`صباحك يا محمد 👋`:`Good day, Mohammed 👋`,state.lang==='ar'?`نظامك اليومي يتغير معك يومًا بيوم.`:`Your system adapts to the day instead of forcing the day into a template.`)}
<div class="grid grid-4"><div class="card hero" style="grid-column:span 2"><div class="hero-row"><div><div class="eyebrow">LIFE PULSE</div><h2>${sc}/100</h2><p class="muted">${sc>=80?'Strong day — keep the rhythm.':sc>=60?'Balanced enough — protect the important blocks.':'Reset gently — choose one high-impact action first.'}</p><div class="kpi-strip"><div class="kpi"><b>${state.water}</b><span>Water</span></div><div class="kpi"><b>${state.walk}</b><span>Walk min</span></div><div class="kpi"><b>${state.studyMinutes}</b><span>Study min</span></div></div></div><div class="score-ring" style="--score:${sc*3.6}deg"><span>${sc}</span></div></div></div>
${metric('😴',state.sleep.hours+'h','Sleep')} ${metric('📚',state.studyMinutes+'m','Study')} ${metric('💧',state.water+'/'+state.waterGoal,'Water')}</div>
<div class="grid grid-3" style="margin-top:16px"><section class="card"><div class="card-head"><h3>🕌 Prayer Anchors</h3><span class="mini">${Object.values(state.prayer).filter(Boolean).length}/5</span></div>${PRAYERS.map(p=>`<div class="row"><div class="row-main"><strong>${p}</strong><small>${state.prayer[p]?'Completed':'Not logged'}</small></div><button class="check ${state.prayer[p]?'done':''}" data-prayer="${p}">${state.prayer[p]?'✓':''}</button></div>`).join('')}</section>
<section class="card"><div class="card-head"><h3>🎯 Today's 3</h3><button class="btn soft" data-view="planner">Plan</button></div>${(state.priorities.slice(0,3).length?state.priorities.slice(0,3).map((p,i)=>`<div class="row"><div class="row-main"><strong>${i+1}. ${esc(p.title)}</strong><small>${esc(p.when||'Today')}</small></div><button class="check ${p.done?'done':''}" data-priority="${p.id}">${p.done?'✓':''}</button></div>`).join(''):`<div class="empty">Choose three outcomes that would make today feel successful.</div>`)}</section>
<section class="card"><div class="card-head"><h3>⏭️ Coming Up</h3><button class="btn soft" data-view="planner">All</button></div>${upcoming.length?`<div class="list">${upcoming.map(x=>`<div class="row"><div class="row-main"><strong>${esc(x.title||x.name)}</strong><small>${x.date}${x.time?' • '+x.time:''}</small></div><span class="tag ${x.type==='exam'?'red':''}">${x.type||'event'}</span></div>`).join('')}</div>`:`<div class="empty">No future items yet.</div>`}</section></div>
<div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-head"><h3>⚡ Quick Check-in</h3><span class="mini">under 60 seconds</span></div><div class="form-grid"><div class="field"><label>Mood · 1–5</label><input class="input" type="range" min="1" max="5" value="${state.mood}" data-field="mood"></div><div class="field"><label>Energy · 1–5</label><input class="input" type="range" min="1" max="5" value="${state.energy}" data-field="energy"></div><div class="field"><label>Walk minutes</label><input class="input" type="number" min="0" value="${state.walk}" data-field="walk"></div><div class="field"><label>Study minutes</label><input class="input" type="number" min="0" value="${state.studyMinutes}" data-field="studyMinutes"></div></div><div style="margin-top:12px"><label class="mini">Water</label><div class="btn-row" style="margin-top:7px">${[1,2,3,4,5,6,7,8].map(n=>`<button class="btn ${n<=state.water?'primary':''}" data-water="${n}">${n}</button>`).join('')}</div></div></section>
<section class="card"><div class="card-head"><h3>🌤️ Daily Brief</h3><span class="tag green">Adaptive</span></div><p class="quote">${dailyBrief()}</p><div class="progress" style="margin-top:15px"><span style="width:${sc}%"></span></div><p class="mini" style="margin-top:7px">Life Pulse updates from your actual logs — not guesses.</p></section></div>`}
function metric(icon,val,label){return `<div class="card"><div style="font-size:22px">${icon}</div><div class="metric">${val}</div><div class="metric-label">${label}</div></div>`}
function dailyBrief(){const parts=[];if(state.sleep.hours<6.5)parts.push('Protect recovery today: keep the plan lighter and prioritize sleep tonight.');else if(state.sleep.hours>=8)parts.push('Sleep is giving you a solid base today.');if(state.studyMinutes<60)parts.push('A single 25-minute study block is enough to create momentum.');if(state.walk<20)parts.push('A short walk is your easiest movement win.');if(state.water<3)parts.push('Hydration is behind — use the quick buttons instead of waiting.');if(!parts.length)parts.push('Your inputs look balanced. Keep the next important block small, clear and protected.');return parts.slice(0,2).join(' ')}
function planner(){const ev=[...state.events,...state.exams.map(x=>({...x,type:'exam'})),...state.assignments.map(x=>({...x,type:'assignment'}))];return `${head('TIME SYSTEM','Planner','A calm timeline for university, personal tasks, walking, study and future commitments.')}
<div class="grid grid-2"><section class="card"><div class="card-head"><h3>➕ Add future item</h3></div><form id="eventForm" class="form-grid"><div class="field"><label>Title</label><input class="input" name="title" required></div><div class="field"><label>Type</label><select name="type"><option>event</option><option>study</option><option>appointment</option><option>personal</option></select></div><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${todayKey()}" required></div><div class="field"><label>Time</label><input class="input" type="time" name="time"></div><div class="field span-2"><label>Note</label><input class="input" name="note"></div><div class="span-2"><button class="btn primary">Save to timeline</button></div></form></section><section class="card"><div class="card-head"><h3>🧭 Day Shape</h3><span class="mini">Your ideal anchors</span></div><div class="list"><div class="row"><span>Morning</span><b>Prayer → water → top priority</b></div><div class="row"><span>University</span><b>Classes → capture tasks immediately</b></div><div class="row"><span>Evening</span><b>Walk → review → prepare tomorrow</b></div></div></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>📆 Upcoming Timeline</h3><span class="mini">${ev.length} items</span></div>${ev.length?`<div class="table-wrap"><table><thead><tr><th>When</th><th>Title</th><th>Type</th><th></th></tr></thead><tbody>${ev.sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map((x,i)=>`<tr><td>${x.date} ${x.time||''}</td><td><b>${esc(x.title||x.name)}</b><br><small>${esc(x.note||'')}</small></td><td><span class="tag ${x.type==='exam'?'red':''}">${x.type||'event'}</span></td><td><button class="btn danger" data-delete-event="${x.id||i}">Delete</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Your future is empty on purpose. Add only what deserves a place.</div>`}</section>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🧩 Priority Matrix</h3><span class="mini">Decide before you fill the calendar.</span></div>${matrix()}</section>`}
function matrix(){const qs=[['q1','🔴 Do now','Urgent + important'],['q2','🟡 Schedule','Important + not urgent'],['q3','🟢 Simplify','Urgent + not important'],['q4','🟣 Remove','Not urgent + not important']];return `<div class="matrix">${qs.map(([c,title,sub])=>`<div class="quadrant ${c}"><h4>${title}</h4><small>${sub}</small><div class="list" style="margin-top:8px">${state.tasks.filter(x=>x.q===c).slice(0,4).map(x=>`<div class="row"><span>${esc(x.title)}</span><button class="small-actions" data-delete-task="${x.id}">×</button></div>`).join('')||'<div class="mini">Nothing here.</div>'}</div></div>`).join('')}</div>`}
function university(){return `${head('ACADEMIC COCKPIT','University','Subjects stay editable every term. Nothing is hard-coded.')}
<div class="grid grid-3"><section class="card"><div class="card-head"><h3>📚 Add Subject</h3></div><form id="subjectForm" class="form-grid"><div class="field"><label>Subject</label><input class="input" name="name" required></div><div class="field"><label>Instructor</label><input class="input" name="teacher"></div><div class="field"><label>Room</label><input class="input" name="room"></div><div class="field"><label>Day</label><select name="day">${DAYS.map(d=>`<option>${d}</option>`).join('')}</select></div><div class="field"><label>Start</label><input class="input" type="time" name="start"></div><div class="field"><label>End</label><input class="input" type="time" name="end"></div><div class="span-2"><button class="btn primary">Add subject</button></div></form></section>
<section class="card"><div class="card-head"><h3>📝 Assignment</h3></div><form id="assignmentForm" class="form-grid"><div class="field"><label>Title</label><input class="input" name="title" required></div><div class="field"><label>Subject</label><input class="input" name="subject"></div><div class="field"><label>Due</label><input class="input" type="date" name="date" required></div><div class="field"><label>Priority</label><select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></div><div class="span-2"><button class="btn primary">Add assignment</button></div></form></section>
<section class="card"><div class="card-head"><h3>🧪 Exam</h3></div><form id="examForm" class="form-grid"><div class="field"><label>Exam</label><input class="input" name="title" required></div><div class="field"><label>Subject</label><input class="input" name="subject"></div><div class="field"><label>Date</label><input class="input" type="date" name="date" required></div><div class="field"><label>Time</label><input class="input" type="time" name="time"></div><div class="span-2"><button class="btn primary">Add exam</button></div></form></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🗓️ Weekly Timetable</h3><span class="mini">Editable classes</span></div><div class="table-wrap"><table><thead><tr><th>Day</th><th>Time</th><th>Subject</th><th>Instructor</th><th>Room</th><th></th></tr></thead><tbody>${state.subjects.map(s=>`<tr><td>${s.day}</td><td>${s.start||''}–${s.end||''}</td><td><b>${esc(s.name)}</b></td><td>${esc(s.teacher||'—')}</td><td>${esc(s.room||'—')}</td><td><button class="btn danger" data-del-subject="${s.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">Add your current term subjects.</div></td></tr>'}</tbody></table></div></section>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🎯 Academic Progress</h3><button class="btn soft" data-action="add-grade">Add grade</button></div><div class="grid grid-2"><div><div class="metric">${gpa()}</div><div class="metric-label">Current average / GPA estimate</div><div class="progress" style="margin-top:12px"><span style="width:${Math.min(100,gpa()*25)}%"></span></div></div><div class="list">${state.grades.slice(-5).reverse().map(g=>`<div class="row"><span>${esc(g.subject)} — ${esc(g.item)}</span><b>${g.score}/${g.max}</b></div>`).join('')||'<div class="empty">No grades logged yet.</div>'}</div></div></section>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>📌 Assignments & Exams</h3></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Item</th><th>Subject</th><th>Date</th></tr></thead><tbody>${[...state.assignments.map(x=>({...x,type:'Assignment'})),...state.exams.map(x=>({...x,type:'Exam'}))].sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<tr><td>${x.type}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.subject||'—')}</td><td>${x.date}</td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">Nothing scheduled.</div></td></tr>'}</tbody></table></div></section>`}
function gpa(){if(!state.grades.length)return '—';const pct=state.grades.reduce((a,g)=>a+(Number(g.score)||0)/Math.max(1,Number(g.max)||100),0)/state.grades.length;return (pct*4).toFixed(2)}
function health(){return `${head('BODY & RECOVERY','Health','Track signals across the whole body. This is a personal log, not a diagnosis.')}
<div class="grid grid-3"><section class="card"><div class="card-head"><h3>😴 Sleep</h3></div><div class="form-grid"><div class="field"><label>Hours</label><input class="input" type="number" step="0.1" min="0" max="24" value="${state.sleep.hours}" data-sleep="hours"></div><div class="field"><label>Quality 1–5</label><input class="input" type="range" min="1" max="5" value="${state.sleep.quality}" data-sleep="quality"></div><div class="field"><label>Bedtime</label><input class="input" type="time" value="${state.sleep.bed}" data-sleep="bed"></div><div class="field"><label>Wake time</label><input class="input" type="time" value="${state.sleep.wake}" data-sleep="wake"></div></div></section>
<section class="card"><div class="card-head"><h3>🚶 Movement</h3></div><div class="metric">${state.walk} min</div><div class="progress"><span style="width:${Math.min(100,state.walk/state.walkGoal*100)}%"></span></div><div class="btn-row" style="margin-top:12px">${[10,20,30,45,60].map(x=>`<button class="btn" data-walk="${x}">+${x}</button>`).join('')}</div></section>
<section class="card"><div class="card-head"><h3>💧 Hydration</h3></div><div class="metric">${state.water}/${state.waterGoal}</div><div class="progress"><span style="width:${Math.min(100,state.water/state.waterGoal*100)}%"></span></div><div class="btn-row" style="margin-top:12px"><button class="btn primary" data-water-add="1">+1 glass</button><button class="btn" data-water-add="-1">−1</button></div></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🧍 Whole-Body Log</h3><span class="mini">0–10 intensity</span></div><div class="grid grid-3">${BODY.map(part=>`<div class="row"><div class="row-main"><strong>${part}</strong><small>${state.body[part]||0}/10</small></div><input style="width:110px" type="range" min="0" max="10" value="${state.body[part]||0}" data-body="${part}"></div>`).join('')}</div></section>`}
function habits(){return `${head('CONSISTENCY ENGINE','Habits','Small actions, visible history. No shame-based streaks.')}
<div class="grid grid-2"><section class="card"><div class="card-head"><h3>🔥 Today</h3><span class="mini">${state.habits.filter(h=>h.done).length}/${state.habits.length}</span></div><div class="checklist">${state.habits.map(h=>`<div class="check-row"><input type="checkbox" ${h.done?'checked':''} data-habit="${h.id}"><span>${esc(h.name)}</span></div>`).join('')}</div><form id="habitForm" class="btn-row" style="margin-top:12px"><input class="input" name="name" placeholder="New habit" required><button class="btn primary">Add</button></form></section><section class="card"><div class="card-head"><h3>📈 Habit rhythm</h3></div>${habitBars()}</section></div>`}
function habitBars(){const vals=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=todayKey(d);const h=state.history[k]?.habits||0;vals.push({d,h})}const max=Math.max(1,...vals.map(x=>state.habits.length||1));return `<div class="bar-chart">${vals.map(x=>`<div class="bar" style="height:${Math.max(12,x.h/max*130)}px"><small>${x.d.slice(5)}</small></div>`).join('')}</div>`}
function hygiene(){const items=['Shower','Brush teeth — morning','Brush teeth — night','Face care','Hair care','Nails','Fresh clothes','Room reset'];return `${head('PERSONAL CARE','Hygiene','A simple checklist that keeps the basics visible.')}
<div class="grid grid-2"><section class="card"><div class="card-head"><h3>🧼 Today’s reset</h3><span class="mini">${state.hygiene.filter(Boolean).length}/${items.length}</span></div><div class="checklist">${items.map((x,i)=>`<label class="check-row"><input type="checkbox" ${state.hygiene[i]?'checked':''} data-hygiene="${i}"><span>${x}</span></label>`).join('')}</div><div class="progress" style="margin-top:14px"><span style="width:${state.hygiene.filter(Boolean).length/items.length*100}%"></span></div></section><section class="card"><div class="card-head"><h3>✨ Environment</h3></div><div class="list"><div class="row"><span>Desk</span><span class="tag green">10-minute reset</span></div><div class="row"><span>Room</span><span class="tag">One surface at a time</span></div><div class="row"><span>Phone</span><span class="tag yellow">Remove tomorrow’s noise</span></div></div></section></div>`}
function finance(){const bal=Number(state.income||0)-state.expenses.reduce((a,x)=>a+Number(x.amount||0),0);const remain=Math.max(0,Number(state.savingsTarget||0)-Number(state.savingsSaved||0));return `${head('MONEY SYSTEM','Finance','Track spending without turning your life into a spreadsheet.')}
<div class="grid grid-4">${metric('💵',bal.toFixed(0),'Current balance')} ${metric('🎯',remain.toFixed(0),'Remaining to target')} ${metric('📈',Number(state.savingsTarget||0).toFixed(0),'Savings target')} ${metric('📱',esc(state.phoneTarget),'Phone goal')}</div>
<div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-head"><h3>📱 Phone Savings Goal</h3></div><form id="saveForm" class="form-grid"><div class="field"><label>Goal name</label><input class="input" name="phone" value="${esc(state.phoneTarget)}"></div><div class="field"><label>Target</label><input class="input" type="number" name="target" value="${state.savingsTarget}"></div><div class="field"><label>Saved</label><input class="input" type="number" name="saved" value="${state.savingsSaved}"></div><div class="span-2"><button class="btn primary">Update goal</button></div></form><div class="progress" style="margin-top:14px"><span style="width:${state.savingsTarget?Math.min(100,state.savingsSaved/state.savingsTarget*100):0}%"></span></div></section>
<section class="card"><div class="card-head"><h3>➕ Add expense</h3></div><form id="expenseForm" class="form-grid"><div class="field"><label>Amount</label><input class="input" type="number" step="0.01" name="amount" required></div><div class="field"><label>Category</label><select name="cat"><option>Food</option><option>Transport</option><option>University</option><option>Phone</option><option>Entertainment</option><option>Other</option></select></div><div class="field span-2"><label>Note</label><input class="input" name="note"></div><div class="span-2"><button class="btn primary">Save expense</button></div></form></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🧾 Recent expenses</h3><span class="mini">${state.expenses.length}</span></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Note</th><th>Amount</th></tr></thead><tbody>${state.expenses.slice(-12).reverse().map(x=>`<tr><td>${x.date}</td><td>${x.cat}</td><td>${esc(x.note||'')}</td><td>${Number(x.amount).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">No expenses yet.</div></td></tr>'}</tbody></table></div></section>`}
function focus(){return `${head('DEEP WORK','Focus','Use focused blocks instead of waiting for motivation.')}
<div class="grid grid-2"><section class="card focus-mode"><div class="eyebrow">FOCUS ENGINE</div><div class="timer" id="timer">${time(timer.sec)}</div><div class="btn-row" style="justify-content:center"><button class="btn primary" data-timer="toggle">${timer.running?'Pause':'Start'}</button><button class="btn" data-timer="reset">Reset</button></div><div class="form-grid" style="margin-top:20px"><div class="field"><label style="color:#ddd">Focus minutes</label><input class="input" id="focusMin" type="number" min="5" value="25"></div><div class="field"><label style="color:#ddd">Break minutes</label><input class="input" id="breakMin" type="number" min="1" value="5"></div></div></section><section class="card"><div class="card-head"><h3>📚 Study Log</h3><span class="mini">${state.focus.sessions} sessions</span></div><div class="metric">${state.focus.minutes} min</div><p class="mini">Link focus sessions to a subject or assignment later; for now the system keeps the time honest.</p><div class="progress"><span style="width:${Math.min(100,state.focus.minutes/120*100)}%"></span></div></section></div>`}
function time(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function journal(){return `${head('REFLECTION','Journal','Three tiny logs: what happened, what worked, what matters.')}
<div class="grid grid-3"><section class="card"><h3>📝 Today</h3><textarea data-journal="journal" placeholder="Write freely...">${esc(state.journal)}</textarea></section><section class="card"><h3>🏆 Wins</h3><textarea data-journal="wins" placeholder="What went right today?">${esc(state.wins)}</textarea></section><section class="card"><h3>🌱 Gratitude</h3><textarea data-journal="gratitude" placeholder="Three things worth noticing...">${esc(state.gratitude)}</textarea></section></div>`}
function analytics(){const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=todayKey(d);days.push({k,...(state.history[k]|| (k===todayKey()?snapshot(state):{}))})}const avg=k=>Math.round(days.reduce((a,d)=>a+(Number(d[k])||0),0)/days.length);return `${head('SYSTEM INTELLIGENCE','Analytics','Patterns, not pressure. The goal is to learn what makes your days work.')}
<div class="grid grid-4">${metric('🧠',avg('study')+'m','Avg study/day')} ${metric('🚶',avg('walk')+'m','Avg walk/day')} ${metric('💧',avg('water').toFixed(1),'Avg water/day')} ${metric('🔥',avg('habits')+'','Avg habits/day')}</div>
<div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-head"><h3>📚 Study trend</h3></div><div class="bar-chart">${days.map(d=>`<div class="bar" style="height:${Math.max(10,Math.min(150,(d.study||0)/120*150))}px"><small>${d.k.slice(5)}</small></div>`).join('')}</div></section><section class="card"><div class="card-head"><h3>🌡️ Balance</h3></div><div class="ring-grid">${[['Sleep',avg('sleep'),8],['Mood',avg('mood'),5],['Energy',avg('energy'),5]].map(x=>`<div class="ring-mini"><div class="circle" style="--v:${Math.min(100,x[1]/x[2]*100)}%"><div class="circle-inner">${x[1]}</div></div><small>${x[0]}</small></div>`).join('')}</div><p class="mini" style="margin-top:14px">Use this to adjust your routine, not to judge yourself.</p></section></div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>🔎 Personal patterns</h3></div><div class="list">${insights(days).map(x=>`<div class="row"><div class="row-main"><strong>${x.title}</strong><small>${x.text}</small></div><span class="tag ${x.kind||''}">${x.kind==='green'?'Good':'Insight'}</span></div>`).join('')}</div></section>`}
function insights(days){const out=[];const s=days.map(x=>x.study||0),w=days.map(x=>x.walk||0);if(Math.max(...s)>=90)out.push({title:'Your study system has a repeatable ceiling.',text:'You already have days with 90+ minutes. Build around the conditions of those days rather than forcing a huge target.',kind:'green'});if(Math.max(...w)>=30)out.push({title:'Walking is a realistic movement anchor.',text:'Use it as your default low-friction activity when you are not training.',kind:'green'});if(state.savingsTarget>0)out.push({title:'Your phone goal is now a visible project.',text:`${Math.max(0,state.savingsTarget-state.savingsSaved).toFixed(0)} remains. Treat savings as a planned line, not leftover money.`});out.push({title:'University subjects are intentionally user-managed.',text:'Change the term without rebuilding the system. Classes, assignments and exams stay linked to the current term.'});return out}
function music(){
const yt=state.music?.youtube||''; const audio=state.music?.audioUrl||'';
return `${head('MEDIA ROOM',state.lang==='ar'?'الموسيقى والقرآن':'Music & Quran',state.lang==='ar'?'مشغل واحد للأغاني والقرآن مع خلفية حقيقية.':'A focused player for songs and Quran, with real photographic backgrounds.')}
<div class="grid grid-2">
<section class="card music-player"><div class="card-head"><h3>🎧 ${state.lang==='ar'?'مشغل الصوت':'Audio Player'}</h3><span class="tag green">HTML5</span></div>
<p class="mini">${state.lang==='ar'?'ارفع ملف MP3/M4A/WAV من جهازك أو ضع رابط ملف صوتي مباشر.':'Upload MP3/M4A/WAV or use a direct audio URL.'}</p>
<input class="input" id="audioFile" type="file" accept="audio/*" style="margin:10px 0">
<div class="form-grid"><div class="field"><label>Audio URL</label><input class="input" id="audioUrl" value="${esc(audio)}" placeholder="https://.../audio.mp3"></div><div class="field"><label>Title</label><input class="input" id="audioTitle" value="${esc(state.music?.title||'My audio')}" placeholder="Quran / Song"></div></div>
<audio id="audioPlayer" controls preload="metadata" style="width:100%;margin-top:12px" src="${esc(audio)}"></audio>
<div class="btn-row" style="margin-top:10px"><button class="btn primary" data-action="save-audio">💾 Save audio</button><button class="btn" data-action="clear-audio">Clear</button></div></section>
<section class="card"><div class="card-head"><h3>▶️ YouTube</h3><span class="tag">Music / Quran</span></div><p class="mini">${state.lang==='ar'?'الصق رابط فيديو أو تسجيل من YouTube وسيظهر داخل التطبيق.':'Paste a YouTube video URL and play it inside the app.'}</p><div class="field"><label>YouTube URL</label><input class="input" id="ytUrl" value="${esc(yt)}" placeholder="https://www.youtube.com/watch?v=..."></div><div class="btn-row" style="margin-top:10px"><button class="btn primary" data-action="load-youtube">▶️ Play</button></div>${yt?`<div class="youtube-wrap" style="margin-top:14px"><iframe id="ytFrame" src="https://www.youtube.com/embed/${youtubeId(yt)}?playsinline=1&rel=0" title="YouTube player" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>`:`<div class="empty" style="margin-top:14px">${state.lang==='ar'?'أضف رابط YouTube لتشغيله هنا.':'Add a YouTube URL to play it here.'}</div>`}</section>
</div>
<section class="card" style="margin-top:16px"><div class="card-head"><h3>📂 ${state.lang==='ar'?'ملفاتك الصوتية':'Your audio'}</h3><span class="mini">${state.music?.title||'No saved title'}</span></div><div class="row"><div class="row-main"><strong>🎵 ${esc(state.music?.title||'Local / direct audio')}</strong><small>${audio?'Ready to play':'No audio URL saved'}</small></div><button class="btn soft" data-action="open-audio">Open</button></div></section>`
}
function youtubeId(url){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1).split('/')[0];if(u.searchParams.get('v'))return u.searchParams.get('v');const m=u.pathname.match(/embed\/([^/]+)/);return m?m[1]:''}catch{return ''}}

function settings(){return `${head('CONTROL ROOM','Settings','Make the system feel like yours.')}
<div class="grid grid-2"><section class="card"><h3>🎨 Appearance</h3><div class="form-grid"><div class="field"><label>Theme</label><select data-setting="theme"><option value="aurora" ${state.theme==='aurora'?'selected':''}>Aurora</option><option value="sunrise" ${state.theme==='sunrise'?'selected':''}>Sunrise</option><option value="ocean" ${state.theme==='ocean'?'selected':''}>Ocean</option><option value="night" ${state.theme==='night'?'selected':''}>Night</option></select></div><div class="field"><label>Real photo background</label><select data-setting="background"><option value="aurora" ${state.background==='aurora'?'selected':''}>Aurora / Landscape</option><option value="night" ${state.background==='night'?'selected':''}>Night Sky</option><option value="mountain" ${state.background==='mountain'?'selected':''}>Mountain</option><option value="sea" ${state.background==='sea'?'selected':''}>Sea</option><option value="none" ${state.background==='none'?'selected':''}>No photo</option></select></div><div class="field"><label>Language</label><select data-setting="lang"><option value="en" ${state.lang==='en'?'selected':''}>English</option><option value="ar" ${state.lang==='ar'?'selected':''}>العربية</option></select></div></div></section><section class="card"><h3>🔊 Experience</h3><label class="check-row"><input type="checkbox" data-setting-bool="sound" ${state.settings.sound?'checked':''}><span>Interaction sounds</span></label><label class="check-row"><input type="checkbox" data-setting-bool="notifications" ${state.settings.notifications?'checked':''}><span>Notification preference</span></label></section>
<section class="card"><h3>📍 Prayer location</h3><form id="cityForm" class="form-grid"><div class="field"><label>City</label><input class="input" name="city" value="${esc(state.city)}" required></div><div class="field"><label>Country</label><input class="input" name="country" value="${esc(state.country)}"></div><div class="span-2"><button class="btn primary">Load prayer times</button></div></form><div id="prayerTimes" style="margin-top:12px">${prayerTimesHTML()}</div></section>
<section class="card"><h3>💾 Data</h3><p class="mini">Your data is stored locally in this browser.</p><div class="btn-row"><button class="btn primary" data-action="export">Export JSON</button><button class="btn" data-action="import">Import JSON</button><button class="btn danger" data-action="reset">Reset all</button></div><input type="file" id="importFile" accept="application/json" hidden></section></div>`}
function prayerTimesHTML(){return state.lastPrayer?`<div class="list">${PRAYERS.map(p=>`<div class="row"><span>${p}</span><b>${state.lastPrayer[p]||'—'}</b></div>`).join('')}</div>`:`<div class="empty">Enter your city and load today’s prayer times.</div>`}
function bind(){
$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$('#sidebar').classList.remove('open');render()});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#quickBtn').onclick=()=>quick();$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#langBtn').onclick=()=>{state.lang=state.lang==='en'?'ar':'en';save();render()};$('#themeBtn').onclick=()=>{state.theme=state.theme==='night'?'aurora':'night';applyTheme();save();render()};
$$('[data-prayer]').forEach(b=>b.onclick=()=>{state.prayer[b.dataset.prayer]=!state.prayer[b.dataset.prayer];sound();save();render()});
$$('[data-priority]').forEach(b=>b.onclick=()=>{const p=state.priorities.find(x=>String(x.id)===String(b.dataset.priority));if(p)p.done=!p.done;save();render()});
$$('[data-water]').forEach(b=>b.onclick=()=>{state.water=Number(b.dataset.water);save();render()});$$('[data-water-add]').forEach(b=>b.onclick=()=>{state.water=Math.max(0,state.water+Number(b.dataset.waterAdd));save();render()});$$('[data-walk]').forEach(b=>b.onclick=()=>{state.walk+=Number(b.dataset.walk);save();render()});
$$('[data-habit]').forEach(i=>i.onchange=()=>{const h=state.habits.find(x=>String(x.id)===String(i.dataset.habit));if(h)h.done=i.checked;save();render()});$$('[data-hygiene]').forEach(i=>i.onchange=()=>{state.hygiene[i.dataset.hygiene]=i.checked;save();render()});
$$('[data-body]').forEach(i=>i.oninput=()=>{state.body[i.dataset.body]=Number(i.value);i.parentElement.querySelector('small').textContent=i.value+'/10';save()});$$('[data-sleep]').forEach(i=>i.onchange=()=>{state.sleep[i.dataset.sleep]=i.type==='number'?Number(i.value):i.value;save()});
$$('[data-field]').forEach(i=>i.oninput=()=>{state[i.dataset.field]=Number(i.value);save()});$$('[data-journal]').forEach(i=>i.oninput=()=>{state[i.dataset.journal]=i.value;save()});
$$('[data-delete-event]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteEvent;state.events=state.events.filter(x=>String(x.id)!==String(id));save();render()});$$('[data-del-subject]').forEach(b=>b.onclick=()=>{state.subjects=state.subjects.filter(x=>String(x.id)!==String(b.dataset.delSubject));save();render()});
$$('[data-timer]').forEach(b=>b.onclick=()=>{if(b.dataset.timer==='toggle'){timer.running=!timer.running;timer.running?startTimer():stopTimer();render()}else{stopTimer();timer.sec=25*60;render()}});
$$('[data-setting]').forEach(i=>i.onchange=()=>{state[i.dataset.setting]=i.value;save();applyTheme();render()});
const afile=$('#audioFile');if(afile)afile.onchange=e=>{const f=e.target.files?.[0];if(f){const url=URL.createObjectURL(f);$('#audioPlayer').src=url;state.music=state.music||{};state.music.audioUrl=url;state.music.title=f.name;save();toast('Audio loaded')}};
const saveAudio=$('[data-action=save-audio]');if(saveAudio)saveAudio.onclick=()=>{state.music=state.music||{};state.music.audioUrl=$('#audioUrl').value||state.music.audioUrl||'';state.music.title=$('#audioTitle').value||'My audio';save();render();toast('Audio saved')};
const clearAudio=$('[data-action=clear-audio]');if(clearAudio)clearAudio.onclick=()=>{state.music=state.music||{};state.music.audioUrl='';state.music.title='';save();render()};
const loadYT=$('[data-action=load-youtube]');if(loadYT)loadYT.onclick=()=>{const u=$('#ytUrl').value;const id=youtubeId(u);if(!id)return toast('Invalid YouTube URL');state.music=state.music||{};state.music.youtube=u;save();render()};
const openAudio=$('[data-action=open-audio]');if(openAudio)openAudio.onclick=()=>{const a=$('#audioPlayer');if(a){a.play().catch(()=>{});a.scrollIntoView({behavior:'smooth',block:'center'})}};$$('[data-setting-bool]').forEach(i=>i.onchange=()=>{state.settings[i.dataset.settingBool]=i.checked;save()});
const ef=$('#eventForm');if(ef)ef.onsubmit=e=>{e.preventDefault();const f=new FormData(ef);state.events.push({id:Date.now(),title:f.get('title'),type:f.get('type'),date:f.get('date'),time:f.get('time'),note:f.get('note')});save();toast('Added to timeline');render()};
const sf=$('#subjectForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const f=new FormData(sf);state.subjects.push({id:Date.now(),...Object.fromEntries(f)});save();toast('Subject added');render()};
const af=$('#assignmentForm');if(af)af.onsubmit=e=>{e.preventDefault();const f=new FormData(af);state.assignments.push({id:Date.now(),...Object.fromEntries(f)});save();toast('Assignment added');render()};
const xf=$('#examForm');if(xf)xf.onsubmit=e=>{e.preventDefault();const f=new FormData(xf);state.exams.push({id:Date.now(),...Object.fromEntries(f)});save();toast('Exam added');render()};
const hf=$('#habitForm');if(hf)hf.onsubmit=e=>{e.preventDefault();const f=new FormData(hf);state.habits.push({id:Date.now(),name:f.get('name'),done:false});save();render()};
const ex=$('#expenseForm');if(ex)ex.onsubmit=e=>{e.preventDefault();const f=new FormData(ex);state.expenses.push({date:todayKey(),...Object.fromEntries(f)});save();toast('Expense saved');render()};
const sv=$('#saveForm');if(sv)sv.onsubmit=e=>{e.preventDefault();const f=new FormData(sv);state.phoneTarget=f.get('phone');state.savingsTarget=Number(f.get('target'));state.savingsSaved=Number(f.get('saved'));save();toast('Savings goal updated');render()};
const cf=$('#cityForm');if(cf)cf.onsubmit=async e=>{e.preventDefault();const f=new FormData(cf);state.city=f.get('city');state.country=f.get('country');save();await loadPrayer();render()};
$$('[data-action="quick"]').forEach(b=>b.onclick=quick);$$('[data-action="add-grade"]').forEach(b=>b.onclick=gradeModal);$$('[data-action="export"]').forEach(b=>b.onclick=exportData);$$('[data-action="import"]').forEach(b=>b.onclick=()=>$('#importFile').click());$$('[data-action="reset"]').forEach(b=>b.onclick=()=>{if(confirm('Reset all local data?')){localStorage.removeItem(KEY);state=load();render()}});const imp=$('#importFile');if(imp)imp.onchange=importData;
const addRem=$('#addRem');if(addRem)addRem.onclick=()=>{const title=$('#remTitle').value,at=$('#remAt').value;if(!title||!at)return toast('Enter title and time');state.reminders=state.reminders||[];state.reminders.push({id:Date.now(),title,at});save();if(state.settings.notifications&&'Notification' in window)Notification.requestPermission().catch(()=>{});toast('Reminder saved');render()};
const notifyBtn=$('#notifyBtn');if(notifyBtn)notifyBtn.onclick=async()=>{if(!('Notification' in window))return toast('Notifications are not supported');const p=await Notification.requestPermission();state.settings.notifications=p==='granted';save();toast(p==='granted'?'Notifications enabled':'Permission not granted')};
}
function quick(){openModal('Quick Add',`<form id="quickForm" class="form-grid"><div class="field"><label>What?</label><input class="input" name="title" required></div><div class="field"><label>Type</label><select name="type"><option>task</option><option>event</option><option>study</option><option>habit</option></select></div><div class="field span-2"><label>Date</label><input class="input" type="date" name="date" value="${todayKey()}"></div><div class="span-2"><button class="btn primary">Add</button></div></form>`);$('#quickForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),type=f.get('type'),title=f.get('title');if(type==='task')state.tasks.push({id:Date.now(),title,done:false,q:'q2',date:f.get('date')});else if(type==='habit')state.habits.push({id:Date.now(),name:title,done:false});else state.events.push({id:Date.now(),title,type,date:f.get('date')});save();sound();$('#modal').classList.add('hidden');toast('Added');render()}}
function gradeModal(){openModal('Add grade',`<form id="gradeForm" class="form-grid"><div class="field"><label>Subject</label><input class="input" name="subject" required></div><div class="field"><label>Assessment</label><input class="input" name="item" required></div><div class="field"><label>Score</label><input class="input" type="number" name="score" required></div><div class="field"><label>Max</label><input class="input" type="number" name="max" value="100" required></div><div class="span-2"><button class="btn primary">Save grade</button></div></form>`);$('#gradeForm').onsubmit=e=>{e.preventDefault();state.grades.push(Object.fromEntries(new FormData(e.target)));save();$('#modal').classList.add('hidden');render()}}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function startTimer(){clearInterval(timer.id);timer.id=setInterval(()=>{timer.sec--;const el=$('#timer');if(el)el.textContent=time(timer.sec);if(timer.sec<=0){stopTimer();state.focus.sessions++;const mins=Number($('#focusMin')?.value||25);state.focus.minutes+=mins;state.studyMinutes+=mins;save();sound();toast('Focus block complete 🎉');timer.sec=5*60;timer.mode='break';render()}},1000)}function stopTimer(){clearInterval(timer.id);timer.id=null;timer.running=false}
async function loadPrayer(){try{const city=encodeURIComponent(state.city),country=encodeURIComponent(state.country);const d=new Date();const url=`https://api.aladhan.com/v1/timingsByCity/${String(d.getDate()).padStart(2,'0')}-${String(d.getMonth()+1).padStart(2,'0')}-${d.getFullYear()}?city=${city}&country=${country}&method=5`;const r=await fetch(url);const j=await r.json();if(j.code===200){state.lastPrayer={Fajr:j.data.timings.Fajr,Dhuhr:j.data.timings.Dhuhr,Asr:j.data.timings.Asr,Maghrib:j.data.timings.Maghrib,Isha:j.data.timings.Isha};save();toast('Prayer times updated')}else throw 0}catch{toast('Could not load prayer times — check city or connection')}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mohammed-life-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState,...JSON.parse(r.result)};normalize(state);save();render();toast('Data imported')}catch{toast('Invalid backup')}};r.readAsText(f)}
function applyTheme(){document.body.dataset.theme=state.theme;document.body.dataset.background=state.background||'aurora'}
applyTheme();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
